### FinanceDataReader 란?
* 한국 주식 가격, 미국주식 가격, 지수, 환율, 암호화폐 가격, 종목 리스팅 등 금융 데이터 수집 라이브러리

* FinanceData/FinanceDataReader: Financial data reader

* FinanceDataReader 사용자 안내서 | FinanceData

* https://pandas-datareader.readthedocs.io/en/latest/readers/index.html

### 설치

In [5]:
import pandas as pd 
#1점 대 버전 이상이면 상관없다. 
pd.__version__

'1.1.3'

In [ ]:
# 
#pip install pandas -- upgrade

In [17]:
import FinanceDataReader as fdr
fdr.__version__

'0.9.31'

## 한국거래소 상장종목 가져오기

In [10]:
fdr.StockListing?


#Output: 
# Signature: fdr.StockListing(market)
# Docstring:
# read stock list of stock exchanges
# * market: 'S&P500', 'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE', 
#         'KRX', 'KOSPI', 'KOSDAQ', 'KONEX'
#         'KRX-DELISTING', 'KRX-MARCAP', 'KRX-ADMINISTRATIVE'
#         'ETF/KR'
# File:      c:\users\dell\anaconda3\lib\site-packages\financedatareader\data.py
# Type:      function

### 한국거래소 상장종목 전체 가져오기

In [20]:
df_krx = fdr.StockListing("KRX")  #우리가 매번 가져올 수 없으니까 변수에 넣어준다. 
df_krx.shape

(7140, 10)

In [21]:
df_krx.head()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도

In [22]:
df_krx.describe()

<ipython-input-22-8453f2ac474b>:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df_krx.describe()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
count,7140,7140,7140,2450,2431,2450,2450,2450,2270,2450
unique,7140,3,7140,160,2274,1808,9,2328,2249,22
top,086710,KOSPI,대신증권우,특수 목적용 기계 제조업,기업인수합병,1976-06-30 00:00:00,12월,-,http://www.eagon.com,서울특별시
freq,1,5475,1,143,38,8,2390,5,2,991
first,NaN,NaN,NaN,NaN,NaN,1956-03-03 00:00:00,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,2021-07-22 00:00:00,NaN,NaN,NaN,NaN

In [24]:
df_krx.to_csv("krx.csv", index = False)  #index = False: 열에 unnamed 라고 쓰인 인덱스 열을 빼기 위해 작성

In [26]:
pd.read_csv("krx.csv")

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,박대현,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
7135,000547,KOSPI,흥국화재2우B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7136,000545,KOSPI,흥국화재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7137,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
7138,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호 (각자대표)",http://www.heerim.com,서울특별시
7139,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시